services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_DB: InventoryManager
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: '#$%PostgreSQL!'
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    webapi:
        image: ${{ secrets.DOCKER_USERNAME }}/InventoryManagerBackend:latest
        container_name: webapi
        build:
            context: .
            dockerfile: src/Web.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "5000:80"
        depends_on:
            - postgres

volumes:
    postgres_data: